using System.Text;
using System.Text.Json;
using InterviewAssist.Library.Pipeline.Utterance;

namespace InterviewAssist.Library.Pipeline.Recording;

/// <summary>
/// Plays back a recorded session, feeding events to the pipeline at recorded timing.
/// </summary>
public sealed class SessionPlayer
{
    private readonly List<RecordedEvent> _events = new();
    private readonly JsonSerializerOptions _jsonOptions;

    private CancellationTokenSource? _cts;
    private bool _isPlaying;

    public event Action<RecordedEvent>? OnEventPlayed;
    public event Action<string>? OnInfo;
    public event Action? OnPlaybackComplete;

    public SessionConfig? SessionConfig { get; private set; }
    public bool IsPlaying => _isPlaying;
    public int TotalEvents => _events.Count;
    public int CurrentEventIndex { get; private set; }

    public SessionPlayer()
    {
        _jsonOptions = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };
    }

    /// <summary>
    /// Load a recorded session from a JSONL file.
    /// </summary>
    public async Task LoadAsync(string filePath, CancellationToken ct = default)
    {
        _events.Clear();
        SessionConfig = null;
        CurrentEventIndex = 0;

        using var reader = new StreamReader(filePath, Encoding.UTF8);
        string? line;
        int lineNumber = 0;

        while ((line = await reader.ReadLineAsync(ct)) != null)
        {
            lineNumber++;
            if (string.IsNullOrWhiteSpace(line)) continue;

            try
            {
                var evt = JsonSerializer.Deserialize<RecordedEvent>(line, _jsonOptions);
                if (evt == null) continue;

                if (evt is RecordedSessionMetadata metadata)
                {
                    SessionConfig = metadata.Config;
                }

                _events.Add(evt);
            }
            catch (JsonException ex)
            {
                OnInfo?.Invoke($"Warning: Failed to parse line {lineNumber}: {ex.Message}");
            }
        }

        OnInfo?.Invoke($"Loaded {_events.Count} events from {Path.GetFileName(filePath)}");
    }

    /// <summary>
    /// Play back the loaded session, feeding ASR events to the pipeline at recorded timing.
    /// </summary>
    public async Task PlayAsync(UtteranceIntentPipeline pipeline, CancellationToken ct = default)
    {
        if (_events.Count == 0)
        {
            throw new InvalidOperationException("No events loaded. Call LoadAsync first.");
        }

        _cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
        _isPlaying = true;
        CurrentEventIndex = 0;
        var token = _cts.Token;

        try
        {
            long previousOffsetMs = 0;

            foreach (var evt in _events)
            {
                token.ThrowIfCancellationRequested();

                // Skip metadata during playback
                if (evt is RecordedSessionMetadata)
                {
                    CurrentEventIndex++;
                    continue;
                }

                // Wait for appropriate delay to simulate realtime
                var delayMs = evt.OffsetMs - previousOffsetMs;
                if (delayMs > 0)
                {
                    await Task.Delay((int)delayMs, token);
                }
                previousOffsetMs = evt.OffsetMs;

                // Dispatch event to pipeline (only input events)
                DispatchEvent(evt, pipeline);
                OnEventPlayed?.Invoke(evt);
                CurrentEventIndex++;
            }

            OnInfo?.Invoke("Playback complete");
            OnPlaybackComplete?.Invoke();
        }
        catch (OperationCanceledException)
        {
            OnInfo?.Invoke("Playback cancelled");
        }
        finally
        {
            _isPlaying = false;
        }
    }

    private void DispatchEvent(RecordedEvent evt, UtteranceIntentPipeline pipeline)
    {
        switch (evt)
        {
            case RecordedAsrEvent asr:
                // Feed ASR event to pipeline - this is the input that drives intent detection
                pipeline.ProcessAsrEvent(new AsrEvent
                {
                    Text = asr.Data.Text,
                    IsFinal = asr.Data.IsFinal,
                    SpeakerId = asr.Data.SpeakerId,
                    IsUtteranceEnd = asr.Data.IsUtteranceEnd
                });
                break;

            case RecordedUtteranceEndSignal:
                // Signal utterance end to pipeline
                pipeline.SignalUtteranceEnd();
                break;

            // Note: UtteranceEvent, IntentEvent, ActionEvent are OUTPUT events
            // They are re-generated by the pipeline during playback
            // We record them for analysis comparison but don't replay them
        }
    }

    /// <summary>
    /// Stop playback.
    /// </summary>
    public void Stop()
    {
        _cts?.Cancel();
    }
}
